export const LIST_MOCKS = [
  {
    body: "Lorem Ipsum #10200 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'wanderson@gmail.com',
      firstname: 'William',
      lastname: 'Anderson',
      phone: '0652109984',
    },
    date: '2022-07-22T14:03:16.959739',
    id: 10200,
    read: false,
    subject: 'SMS #10200',
    type: 'sms',
  },
  {
    body: "Lorem Ipsum #10201 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'rdavis@gmail.com',
      firstname: 'Robert',
      lastname: 'Davis',
      phone: '0623131022',
    },
    date: '2022-07-21T14:03:16.959745',
    id: 10201,
    read: false,
    subject: 'Appel #10201',
    type: 'phone',
  },
  {
    body: "Lorem Ipsum #10202 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'janderson@gmail.com',
      firstname: 'Joseph',
      lastname: 'Anderson',
      phone: '0660370659',
    },
    date: '2022-07-21T14:03:16.959749',
    id: 10202,
    read: true,
    subject: 'SMS #10202',
    type: 'sms',
  },
  {
    body: "Lorem Ipsum #10203 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'rwilliams@gmail.com',
      firstname: 'Richard',
      lastname: 'Williams',
      phone: '0674890218',
    },
    date: '2022-07-20T14:03:16.959754',
    id: 10203,
    read: false,
    subject: 'Email #10203',
    type: 'email',
  },
  {
    body: "Lorem Ipsum #10204 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'tmiller@gmail.com',
      firstname: 'Thomas',
      lastname: 'Miller',
      phone: '0611872169',
    },
    date: '2022-07-16T14:03:16.959759',
    id: 10204,
    read: false,
    subject: 'SMS #10204',
    type: 'sms',
  },
  {
    body: "Lorem Ipsum #10205 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'mthomas@gmail.com',
      firstname: 'Michael',
      lastname: 'Thomas',
      phone: '0629886349',
    },
    date: '2022-07-18T14:03:16.959764',
    id: 10205,
    read: false,
    subject: 'Email #10205',
    type: 'email',
  },
  {
    body: "Lorem Ipsum #10206 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'cmiller@gmail.com',
      firstname: 'Charles',
      lastname: 'Miller',
      phone: '0648101432',
    },
    date: '2022-06-27T14:03:16.959768',
    id: 10206,
    read: true,
    subject: 'Email #10206',
    type: 'email',
  },
  {
    body: "Lorem Ipsum #10207 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'jwilson@gmail.com',
      firstname: 'James',
      lastname: 'Wilson',
      phone: '0620614506',
    },
    date: '2022-07-04T14:03:16.959772',
    id: 10207,
    read: false,
    subject: 'Appel #10207',
    type: 'phone',
  },
  {
    body: "Lorem Ipsum #10208 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'rjackson@gmail.com',
      firstname: 'Robert',
      lastname: 'Jackson',
      phone: '0661329544',
    },
    date: '2022-06-22T14:03:16.959776',
    id: 10208,
    read: true,
    subject: 'SMS #10208',
    type: 'sms',
  },
  {
    body: "Lorem Ipsum #10209 is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
    contact: {
      email: 'rjones@gmail.com',
      firstname: 'Robert',
      lastname: 'Jones',
      phone: '0632246205',
    },
    date: '2022-07-04T14:03:16.959781',
    id: 10209,
    read: true,
    subject: 'SMS #10209',
    type: 'sms',
  },
];
